backend:
  name: git-gateway
  branch: main

site_url: https://luxovius.netlify.app
logo_url: https://luxovi.us/img/Logo.png
locale: 'nl'
media_folder: public/img
public_folder: /img

collections:
  - name: 'general'
    label: 'General'
    files:
      - name: 'intro'
        label: 'Intro'
        file: 'content/intro.md'
        format: 'frontmatter'
        editor:
          preview: true
        fields:
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - name: 'praesidium'
        label: 'Het Praesidium'
        file: 'content/praesidium.md'
        format: 'frontmatter'
        editor:
          preview: false
        fields:
          - { label: 'Praeses', name: 'praeses', widget: 'relation', collection: 'leden', value_field: 'name', search_fields: [ 'name' ], }
          - { label: 'Ab actis', name: 'abactis', widget: 'relation', collection: 'leden', value_field: 'name', search_fields: ['name'], }
          - { label: 'Quaestor', name: 'quaester', widget: 'relation', collection: 'leden', value_field: 'name', search_fields: ['name'], }
  - name: 'lichtingen'
    label: 'Lichtingen'
    label_singular: 'Lichting'
    folder: 'content/lichtingen'
    format: 'frontmatter'
    create: true
    slug: '{{name}}'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Order', name: 'order', widget: 'number'}
  - name: 'leden'
    label: 'Leden'
    label_singular: 'Lid'
    folder: 'content/leden'
    format: 'frontmatter'
    create: true
    slug: '{{name}}'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Lichting', name: 'lichting', widget: 'relation', collection: 'lichtingen', value_field: 'name', search_fields: ['name'], }
      - { label: 'Type', name: 'type', widget: 'select', options: ['Actief lid', 'Oude lul', 'Erelid'], required: false }
      - { label: 'Old style', name: 'old_style', widget: 'boolean', required: false }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
      - { label: 'Photo', name: 'photo', widget: 'image', media_folder: '/public/img/luxoven', public_folder: '/img/luxoven' }